name: GitHub Pages Deploy with Custom Action

on:
  push:
    branches:
      - main # Adjust to your default branch
  pull_request:
    branches:
      - main # Optional for preview builds

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the code
      - name: Checkout Code
        uses: actions/checkout@v3

      # Step 2: Set up Python environment
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9' # Adjust as needed

      # Step 3: Install dependencies
      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r _python/requirements.txt

      # Step 4: Run build-all.py (custom action)
      - name: Run Custom Build Script
        run: python _python/build-all.py

      # Step 5: Deploy to GitHub Pages
      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v2
        with:
          build_dir: _site # Replace with the output directory of your script
